### ISSUE TITLE
Remove the scrollbar from the Portfolio section

### ISSUE THREAD

**Issue by mohammadshaad** [rohitranjan-2702/dev-landing-page#5]
# The scroll bar from the portfolio section can be removed so that there is uniformity in the UI and the user flow would be smooth

## Home section (Without scroll-bar)
![image](https://github.com/rohitranjan-2702/dev-landing-page/assets/89409389/9fbcc076-293f-4356-8d60-d47637a8f52c)

## Portfolio Section (With Scroll bar)
![image](https://github.com/rohitranjan-2702/dev-landing-page/assets/89409389/06b46050-c9f1-428f-a208-02e3e67f97cc)

Thus the sudden appearance of scroll bar in the portfolio section disturbs the user behaviour while using the site.

**Comment by HassanTanveer** [comment]
Looks like the page is overflowing, I can help if you assign it to me

**Comment by mohammadshaad** [comment]
@HassanTanveer issue is not that I guess. We just need to remove the scroll bars that's it. You can use somple Pseudo class for that.

**Comment by mishba-ai** [comment]
I want to work on this issue. but I'll start working on this after my exam gets over. will it be okay?
 Can you Assign this to me? @mohammadshaad

**Comment by jiyanpatil07** [comment]
Can you assign it to me @mohammadshaad ?

**Comment by Shash-cre-dev** [comment]
I would like to work on this issue asap, I am familiar with this modification of removing the navbar. Can  you assign this issue to me @mohammadshaad ?

**Comment by rohitranjan-2702** [comment]
Do you want to work on this? @jiyanpatil07

**Comment by harshverma2002** [comment]
I have fixed this issue could please once check my pr @rohitranjan-2702
